module.exports = {
  user: ['id', 'name', 'email', 'avatar', 'date'],
  social: [
    'user_id',
    'youtube',
    'twitter',
    'facebook',
    'linkedin',
    'instagram',
  ],
  profile: [
    'id',
    'user_id',
    'company',
    'website',
    'location',
    'status',
    'bio',
    'githubusername',
    'date',
  ],
  posts: ['id', 'user_id', 'text', 'name', 'avatar', 'date'],
  likes: ['user_id', 'post_id', 'name', 'avatar', 'date'],
  experience: [
    'user_id',
    'title',
    'company',
    'location',
    'date_from',
    'date_to',
    'current',
    'description',
  ],
  education: [
    'user_id',
    'school',
    'degree',
    'fieldofstudy',
    'date_from',
    'date_to',
    'current',
    'description',
  ],
  comments: ['user_id', 'post_id', 'name', 'avatar', 'text', 'date'],
  skills: ['user_id', 'skill'],
};
